image:
  repository: pinpointdocker/pinpoint-flink-flink
  tag: dev
  pullPolicy: IfNotPresent
serverPort: 8081
affinity: {}
resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "250m"

zookeeper:
  host: