image:
  repository: pinpointdocker/pinpoint-flink
  tag: 2.5.1
  pullPolicy: IfNotPresent
serverPort: 8081
affinity: {}
resources:
  requests:
    memory: "1Gi"
    cpu: "1"
  limits:
    memory: "1Gi"
    cpu: "1"

zookeeper:
  host: