apiVersion: v1
kind: Service
metadata:
  name: {{ include "zookeeper.fullname" . }}-headless
  labels:
    app.kubernetes.io/name: {{ include "zookeeper.name" . }}
    app.kubernetes.io/component: zookeeper
    {{- include "zookeeper.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - port: 2888
    name: server
  - port: 3888
    name: leader-election
  selector:
    app.kubernetes.io/name: {{ include "zookeeper.name" . }}
    app.kubernetes.io/component: zookeeper
    app.kubernetes.io/instance: {{ .Release.Name }}
