apiVersion: v1
kind: Service
metadata:
  {{- with .Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "pinpoint-zookeeper.fullname" . }}
  labels:
{{ include "pinpoint-zookeeper.labels" . | indent 4 }}
spec:
  ports:
  - port: 2181
    targetPort: 2181
    name: zookeeper-port
