apiVersion: v1
kind: Service
metadata:
  name: {{ include "pinpoint-zookeeper.fullname" . }}-cs
  labels:
    app: {{ include "pinpoint-zookeeper.fullname" . }}
spec:
  ports:
  - port: 2181
    name: client
  selector:
    app: {{ include "pinpoint-zookeeper.fullname" . }}
