replicaCount: 1

podAnnotations:

image:
  repository: pinpointdocker/pinpoint-mysql
  tag: 2.4.2
  pullPolicy: IfNotPresent

rootPassword: root123
user: admin
password: admin
database: pinpoint

resources:

affinity: {}

tolerations: