apiVersion: v1
kind: Service
metadata:
  name: {{ include "server.fullname" . }}-headless
  labels:
    app.kubernetes.io/name: {{ include "server.name" . }}
    app.kubernetes.io/component: pinpoint-server
    {{- include "server.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - port: 2888
    name: server
  - port: 3888
    name: leader-election
  selector:
    app.kubernetes.io/name: {{ include "server.name" . }}
    app.kubernetes.io/component: pinpoint-server
    app.kubernetes.io/instance: {{ .Release.Name }}
