apiVersion: v2
name: pinpoint-receiver
description: A Helm chart for Pinpoint receiver
type: application
# chart version. 
version: 0.1.0
# version number of the application being deployed. 
appVersion: 2.5.2