image:
  repository: kaaskjh/pinpoint-receiver
  tag: 1.0.0
  pullPolicy: IfNotPresent
affinity: {}
tolerations:
resources:
  requests:
    memory: "256Mi"
    cpu: "125m"

slack:
  token:
  channelId:
  attachment:
    title: Pinpoint alarm
    color: "#ff0000"
    titleLink: http://localhost:8080
    # Variable list [pinpointUrl, batchEnv, applicationId, serviceType, userGroupId, userGroupMembers, unit, threshold, notes, sequenceCount, name, value]
    value: "$applicationId, $name, $value"