apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pinpoint-mysql.fullname" . }}
  labels:
{{ include "pinpoint-mysql.labels" . | indent 4 }}

stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.rootPassword }}
  MYSQL_USER: {{ .Values.user }}
  MYSQL_PASSWORD: {{ .Values.password }}
  MYSQL_DATABASE: {{ .Values.database }}