apiVersion: v1
kind: Service
metadata:
  {{- with .Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "pinpoint-mysql.fullname" . }}
  labels:
{{ include "pinpoint-mysql.labels" . | indent 4 }}
spec:
  ports:
  - port: 3306
    name: mysql

  selector:
{{ include "pinpoint-mysql.selectorLabels" . | indent 6 }}
