apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "pinpoint-mysql.labels" . | indent 4 }}
  name: {{ include "pinpoint-mysql.fullname" . }}
spec:
  serviceName: {{ include "pinpoint-mysql.fullname" . }}-headless
  replicas: 1
  selector:
    matchLabels:
{{ include "pinpoint-mysql.selectorLabels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "pinpoint-mysql.labels" . | indent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
          - secretRef:
              name: {{ include "pinpoint-mysql.fullname" .}}
          resources:
{{- toYaml .Values.resources | nindent 12 }}
{{- with .Values.affinity }}
      affinity:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{- toYaml . | nindent 8 }}
{{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        volumeMode: Filesystem
  {{- end }}
