{{- if and (.Values.global.batchEnabled) (.Values.global.webhookEnabled) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "receiver.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "receiver.name" . }}
    {{- include "receiver.labels" . | nindent 4 }}
data:
  SLACK_ATTACHMENT_COLOR: "{{ .Values.slack.attachment.color }}"
  SLACK_ATTACHMENT_TITLE: "{{ .Values.slack.attachment.title }}"
  SLACK_ATTACHMENT_TITLE_LINK: "{{ .Values.slack.attachment.titleLink }}"
  SLACK_ATTACHMENT_VALUE: "{{ .Values.slack.attachment.value }}"
{{- end }}