apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "receiver.fullname" . }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
  labels:
    app.kubernetes.io/name: {{ include "receiver.name" . }}
    app.kubernetes.io/component: pinpoint-server
    {{- include "receiver.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "receiver.name" . }}
      app.kubernetes.io/component: pinpoint-server
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "receiver.name" . }}
        app.kubernetes.io/component: pinpoint-server
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
    spec:
{{- with .Values.affinity }}
      affinity:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{- toYaml . | nindent 8 }}
{{- end }}
      containers:
        - name: pinpoint-receiver
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
{{- toYaml .Values.resources | nindent 12 }}
          ports:
            - name: receiver
              containerPort: 8080