{{- if and (.Values.global.batchEnabled) (.Values.global.webhookEnabled) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "receiver.fullname" . }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
  labels:
    app.kubernetes.io/name: {{ include "receiver.name" . }}
    app.kubernetes.io/component: pinpoint-receiver
    {{- include "receiver.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "receiver.name" . }}
      app.kubernetes.io/component: pinpoint-receiver
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "receiver.name" . }}
        app.kubernetes.io/component: pinpoint-receiver
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
    spec:
{{- with .Values.affinity }}
      affinity:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{- toYaml . | nindent 8 }}
{{- end }}
      containers:
        - name: pinpoint-receiver
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
{{- toYaml .Values.resources | nindent 12 }}
          ports:
            - name: receiver
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: {{ template "receiver.fullname" . }}
            - secretRef:
                name: {{ template "receiver.fullname" . }}
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 2
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 2
{{- end }}