apiVersion: v1
kind: Secret
metadata:
  name: {{ template "receiver.fullname" . }}
  labels:
{{ include "receiver.labels" . | indent 4 }}
type: Opaque
data:
  SLACK_TOKEN: "{{ .Values.slack.token }}"
  SLACK_CHANNEL_ID: "{{ .Values.slack.channelId }}"