{{- if and (.Values.global.batchEnabled) (.Values.global.webhookEnabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "receiver.fullname" . }}
  labels:
{{ include "receiver.labels" . | indent 4 }}
type: Opaque
data:
  SLACK_TOKEN: {{ .Values.slack.token | b64enc | quote }}
  SLACK_CHANNEL_ID: {{ .Values.slack.channelId | b64enc | quote }}
{{- end }}