
pinpoint-web:
  affinity: {}
  ### If you want to use external MySQL or other settings that are different from default values, fill these fields.
  ### When the field is empty, it applies the default value.
  ### Default Value
  ###   mysql.host : pinpoint-mysql
  ###   mysql.port : 3306
  ###   mysql.user : admin
  ###   mysql.password : admin
  mysql:
    host:
    port:
    user:
    password:
    database:

  zookeeper: 
    hostName:

pinpoint-collector:
  affinity: {}

  zookeeper:
    hostName:

pinpoint-zookeeper-hbase:
  affinity: {}

  zookeeper:
    hostName:

pinpoint-mysql:
  rootPassword: root123
  user: admin
  password: admin
  database: pinpoint

  affinity: {}