
pinpoint-server:
  profiles: release
  affinity: {}
  zookeeper:
    image:
      repository: registry.k8s.io/kubernetes-zookeeper
      tag: 1.0-3.4.10
      pullPolicy: IfNotPresent
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "100m"

  hbase:
    image:
      repository: pinpointdocker/pinpoint-hbase
      tag:
      pullPolicy: IfNotPresent
    resources:
      requests:
        memory: "4Gi"
        cpu: "1"
      limits:
        memory: "4Gi"
        cpu: "1"

  collector:
    image:
      repository: pinpointdocker/pinpoint-collector
      tag:
      pullPolicy: IfNotPresent
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "250m"
    receiver:
      grpc:
        agentPort: 9991
        statPort: 9992
        spanPort: 9993
      thrift:
        basePort: 9994
        statPort: 9995
        spanPort: 9996
    loggingLevelRoot: INFO
    clusterEnable: true
    flink:
      enable: false

  web:
    image:
      repository: pinpointdocker/pinpoint-web
      tag: 2.5.1
      pullPolicy: IfNotPresent
    serverPort: 8080
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "250m"
    clusterEnable: true

    adminPassword: admin
    sendUsage: false
    loggingLevelRoot: INFO
    showApplicationStat: true

    batch:
      enable: false
      server: 127.0.0.1
      flink: 127.0.0.1

    mail:
      server:
        url: smtp.gmail.com
        port: 587
        username: username
        password: password
      sender: pinpoint_operator@pinpoint.com
      transportProtocol: smtp
      debug: false
      smtp:
        port: 25
        auth: false
        startTls:
          enable: false
          required: false
  mysql:
    image:
      repository: pinpointdocker/pinpoint-mysql
      tag: 2.5.1
      pullPolicy: IfNotPresent
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "250m"
    rootPassword: root123
    serviceName:
    host:
    port: 3306
    user: admin
    password: admin
    database: pinpoint

  persistence:
    enabled: true
    size: 8Gi