# Default values for hbase
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# The base hadoop image to use for all components.
# See this repo for image build details: https://github.com/Comcast/kube-yarn/tree/master/image
image:
  repository: registry.k8s.io/kubernetes-zookeeper
  tag: 1.0-3.4.10
  pullPolicy: IfNotPresent

# The version of the hadoop libraries being used in the image.
hbaseVersion: 1.2.6
serverPort: 2888
leaderElectionPort: 3888

affinity: {}
tolerations:
serviceType: ClusterIP

replicas: 3

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"

persistence:
  enabled: true
  size: 2Gi