{{- if .Values.global.batchEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "batch.fullname" . }}
  labels:
{{ include "batch.labels" . | indent 4 }}
type: Opaque
data:
  ADMIN_PASSWORD: {{ .Values.adminPassword | b64enc | quote }}
  JDBC_USERNAME: {{ include "batch.mysql.username" . | b64enc | quote }}
  JDBC_PASSWORD: {{ include "batch.mysql.password" . | b64enc | quote }}
{{- end }}