apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "pinpoint-web.fullname" . }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
  labels:
{{ include "pinpoint-web.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "pinpoint-web.selectorLabels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "pinpoint-web.labels" . | indent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      initContainers:
        - name: init-zookeeper
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup {{ include "pinpoint-web.zookeeper.fullname" . }}; do echo waiting for zookeeper; sleep 2; done"]
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: ui
              containerPort: {{ .Values.serverPort }}
          envFrom:
          - configMapRef:
              name: {{ template "pinpoint-web.fullname" . }}
          - secretRef:
              name: {{ template "pinpoint-web.fullname" . }}
          livenessProbe:
            failureThreshold: 3
            tcpSocket:
              port: {{ .Values.serverPort }}
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          readinessProbe:
            failureThreshold: 3
            tcpSocket:
              port: {{ .Values.serverPort }}
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          resources:
{{- toYaml .Values.resources | nindent 12 }}
{{- with .Values.affinity }}
      affinity:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{- toYaml . | nindent 8 }}
{{- end }}
