apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "hbase.fullname" . }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
  labels:
    app.kubernetes.io/name: {{ include "hbase.name" . }}
    app.kubernetes.io/component: master
    {{- include "hbase.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hbase.name" . }}
      app.kubernetes.io/component: master
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
  serviceName: {{ include "hbase.fullname" . }}
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "hbase.name" . }}
        app.kubernetes.io/component: master
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
    spec:
{{- with .Values.affinity }}
      affinity:
{{- toYaml . | nindent 8 }}
{{- end }}
      volumes:
        - name: hbase-config
          configMap:
            name: {{ include "hbase.fullname" . }}
            items:
              - key: hbase-site.xml
                path: hbase-site.xml
      containers:
      - name: pinpoint-hbase
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        resources:
{{ toYaml .Values.hbase.resources | indent 10 }}
        readinessProbe:
          httpGet:
            path: /
            port: 16010
          initialDelaySeconds: 60
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /
            port: 16010
          initialDelaySeconds: 60
          timeoutSeconds: 2
        volumeMounts:
          - name: hbase-config
            mountPath: /opt/hbase/hbase-1.2.6/conf/hbase-site.xml
            subPath: hbase-site.xml
          {{- if .Values.persistence.enabled }}
          - name: data
            mountPath: /home/pinpoint/hbase
          - name: data
            mountPath: /home/pinpoint/zookeeper
          {{- end }}

      - name: pinpoint-zookeeper
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        image: registry.k8s.io/kubernetes-zookeeper:1.0-3.4.10
        resources:
{{ toYaml .Values.zookeeper.resources | indent 10 }}
        ports:
          - containerPort: 2181
            name: client
          - containerPort: 2888
            name: server
          - containerPort: 3888
            name: leader-election
        command:
          - sh
          - -c
          - "start-zookeeper \
      --servers=1 \
      --data_dir=/var/lib/zookeeper/data \
      --data_log_dir=/var/lib/zookeeper/data/log \
      --conf_dir=/opt/zookeeper/conf \
      --client_port=2181 \
      --election_port=3888 \
      --server_port=2888 \
      --tick_time=2000 \
      --init_limit=10 \
      --sync_limit=5 \
      --heap=512M \
      --max_client_cnxns=60 \
      --snap_retain_count=3 \
      --purge_interval=12 \
      --max_session_timeout=40000 \
      --min_session_timeout=4000 \
      --log_level=INFO"
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - "zookeeper-ready 2181"
          initialDelaySeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - "zookeeper-ready 2181"
          initialDelaySeconds: 10
          timeoutSeconds: 5
      {{- if .Values.persistence.enabled }}
        volumeMounts:
          - name: data
            mountPath: /var/lib/zookeeper
      {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        volumeMode: Filesystem
  {{- end }}