apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pinpoint-collector.fullname" . }}
  labels:
{{ include "pinpoint-collector.labels" . | indent 4 }}
data:
  CLUSTER_ENABLE:  "{{ .Values.clusterEnable }}"
  PINPOINT_ZOOKEEPER_ADDRESS: "{{ include "pinpoint-collector.zookeeper.fullname" . }}-0.{{ include "hbase.zookeeper.fullname" . }}-hs,{{ include "pinpoint-collector.zookeeper.fullname" . }}-1.{{ include "hbase.zookeeper.fullname" . }}-hs,{{ include "pinpoint-collector.zookeeper.fullname" . }}-2.{{ include "hbase.zookeeper.fullname" . }}-hs"
  SPRING_PROFILES: "{{ .Values.profiles }}"
  JAVA_OPTS: "-Dspring.profiles.active={{ .Values.profiles }}"
  LOGGING_LEVEL_ROOT:  "{{ .Values.loggingLevelRoot }}"
  FLINK_CLUSTER_ENABLE:  "{{ .Values.flink.enable }}"
  FLINK_CLUSTER_ZOOKEEPER_ADDRESS: "{{ include "pinpoint-collector.zookeeper.fullname" . }}-0.{{ include "hbase.zookeeper.fullname" . }}-hs,{{ include "pinpoint-collector.zookeeper.fullname" . }}-1.{{ include "hbase.zookeeper.fullname" . }}-hs,{{ include "pinpoint-collector.zookeeper.fullname" . }}-2.{{ include "hbase.zookeeper.fullname" . }}-hs"