apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "pinpoint-collector.labels" . | indent 4 }}
  name: {{ include "pinpoint-collector.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "pinpoint-collector.selectorLabels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "pinpoint-collector.labels" . | indent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      initContainers:
        - name: init-zookeeper
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup {{ include "pinpoint-collector.zookeeper.fullname" . }}; do echo waiting for zookeeper; sleep 2; done"]
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
          - configMapRef:
              name: {{ include "pinpoint-collector.fullname" .}}
          ports:
          - containerPort: 9991
            protocol: TCP
          - containerPort: 9992
            protocol: TCP
          - containerPort: 9993
            protocol: TCP
          - containerPort: 9994
            protocol: TCP
          - containerPort: 9995
            protocol: UDP
          - containerPort: 9996
            protocol: UDP
          livenessProbe:
            failureThreshold: 3
            tcpSocket:
              port: 9991
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          readinessProbe:
            failureThreshold: 3
            tcpSocket:
              port: 9991
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          resources:
{{- toYaml .Values.resources | nindent 12 }}
{{- with .Values.affinity }}
      affinity:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{- toYaml . | nindent 8 }}
{{- end }}
