apiVersion: v1
kind: Service
metadata:
  {{- with .Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "pinpoint-collector.fullname" . }}
  labels:
{{ include "pinpoint-collector.labels" . | indent 4 }}
spec:
  ports:
  - port: {{ .Values.receiver.grpc.agentPort}}
    targetPort: 9991
    name: grpc-agent
  - port: {{ .Values.receiver.grpc.statPort}}
    targetPort: 9992
    name: grpc-stat
  - port: {{ .Values.receiver.grpc.spanPort}}
    targetPort: 9993
    name: grpc-span
  - port: {{ .Values.receiver.thrift.basePort}}
    targetPort: 9994
    name: thrift-base
  - port: {{ .Values.receiver.thrift.statPort}}
    targetPort: 9995
    name: thrift-stat
  - port: {{ .Values.receiver.thrift.spanPort}}
    targetPort: 9996
    name: thrift-span

  selector:
{{ include "pinpoint-collector.selectorLabels" . | indent 6 }}
