# Default values for hbase
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# The base hadoop image to use for all components.
# See this repo for image build details: https://github.com/Comcast/kube-yarn/tree/master/image
image:
  repository: pinpointdocker/pinpoint-hbase
  tag: 2.5.2
  pullPolicy: IfNotPresent

# The version of the hadoop libraries being used in the image.
baseDir: /opt/hbase
hbaseVersion: 1.2.6

affinity: {}
tolerations:
serviceType: NodePort
resources:
  requests:
    memory: "4Gi"
    cpu: "1"

persistence:
  enabled: true
  size: 10Gi