# Default values for hbase
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# The base hadoop image to use for all components.
# See this repo for image build details: https://github.com/Comcast/kube-yarn/tree/master/image
image:
  repository: pinpointdocker/pinpoint-hbase
  tag: 2.4.2
  pullPolicy: IfNotPresent

# The version of the hadoop libraries being used in the image.
hbaseVersion: 1.2.6

affinity: {}

hbase:
  master:
    replicas: 1
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"

zookeeper:
  hostName: