apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hbase.fullname" . }}-cm
  labels:
    app.kubernetes.io/name: {{ include "hbase.name" . }}
    {{- include "hbase.labels" . | nindent 4 }}
data:

  hbase-env.sh: |
    # Extra Java runtime options.
    # Below are what we set by default.  May only work with SUN JVM.
    # For more on why as well as other possible settings,
    # see http://hbase.apache.org/book.html#performance
    export HBASE_OPTS="$HBASE_OPTS -XX:+UseConcMarkSweepGC"
  hbase-site.xml: |
    <?xml version="1.0"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
    <configuration>
        <property>
            <name>hbase.rootdir</name>
            <value>file:///home/pinpoint/hbase</value>
        </property>
        <property>
            <name>hbase.cluster.distributed</name>
            <value>true</value>
        </property>
        <property>
            <name>zookeeper.znode.parent</name>
            <value>/hbase</value>
        </property>
        <property>
            <name>hbase.zookeeper.quorum</name>
            <value>{{ include "hbase.zookeeper.fullname" . }}-0.{{ include "hbase.zookeeper.fullname" . }}-hs,{{ include "hbase.zookeeper.fullname" . }}-1.{{ include "hbase.zookeeper.fullname" . }}-hs,{{ include "hbase.zookeeper.fullname" . }}-2.{{ include "hbase.zookeeper.fullname" . }}-hs</value>
        </property>
        <property>
          <name>hbase.zookeeper.property.clientPort</name>
          <value>2181</value>
        </property>
        <property>
          <name>hbase.master.port</name>
          <value>60000</value>
        </property>
        <property>
          <name>hbase.regionserver.port</name>
          <value>60020</value>
        </property>
    </configuration>
