apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hbase.fullname" . }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
  labels:
    app.kubernetes.io/name: {{ include "hbase.name" . }}
    app.kubernetes.io/component: master
    {{- include "hbase.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hbase.name" . }}
      app.kubernetes.io/component: master
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
  replicas: {{ .Values.hbase.master.replicas }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "hbase.name" . }}
        app.kubernetes.io/component: master
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
    spec:
{{- with .Values.affinity }}
      affinity:
{{- toYaml . | nindent 8 }}
{{- end }}
      volumes:
        - name: hbase-config
          configMap:
            name: {{ include "hbase.fullname" . }}-cm
      containers:
      - name: master
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        resources:
{{ toYaml .Values.hbase.master.resources | indent 10 }}
        volumeMounts:
        - name: hbase-config
          mountPath: /tmp/hbase-config