apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hbase-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  volumeMode: Filesystem