apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "hbase.fullname" . }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
  labels:
    app.kubernetes.io/name: {{ include "hbase.name" . }}
    app.kubernetes.io/component: master
    {{- include "hbase.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hbase.name" . }}
      app.kubernetes.io/component: master
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
  serviceName: {{ include "hbase.fullname" . }}
  replicas: {{ .Values.hbase.master.replicas }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "hbase.name" . }}
        app.kubernetes.io/component: master
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
    spec:
{{- with .Values.affinity }}
      affinity:
{{- toYaml . | nindent 8 }}
{{- end }}
      containers:
      - name: master
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        ports:
          - containerPort: 60000
          - containerPort: 16010
        command:
        - "/bin/bash"
        - "/tmp/hbase-config/bootstrap.sh"
        - "-d"
        - "master"
        resources:
{{ toYaml .Values.hbase.master.resources | indent 10 }}
        readinessProbe:
          httpGet:
            path: /
            port: 16010
          initialDelaySeconds: 5
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /
            port: 16010
          initialDelaySeconds: 10
          timeoutSeconds: 2
        volumeMounts:
        - name: hbase-config
          mountPath: /tmp/hbase-config

      - name: regionserver
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        ports:
          - containerPort: 60020
          - containerPort: 16030
        command:
          - "/bin/bash"
          - "/tmp/hbase-config/bootstrap.sh"
          - "-d"
          - "regionserver"
        readinessProbe:
          httpGet:
            path: /
            port: 16030
          initialDelaySeconds: 5
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /
            port: 16030
          initialDelaySeconds: 10
          timeoutSeconds: 2
        volumeMounts:
          - name: hbase-config
            mountPath: /tmp/hbase-config
      volumes:
      - name: hbase-config
        configMap:
          name: {{ include "hbase.fullname" . }}