{{- if .Values.global.batchEnabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flink.fullname" . }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
  labels:
    app.kubernetes.io/name: {{ include "flink.name" . }}
    app.kubernetes.io/component: pinpoint-flink
    {{- include "flink.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "flink.name" . }}
      app.kubernetes.io/component: pinpoint-flink
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "flink.name" . }}
        app.kubernetes.io/component: pinpoint-flink
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
    spec:
{{- with .Values.affinity }}
      affinity:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{- toYaml . | nindent 8 }}
{{- end }}
      volumes:
        - name: docker-bin
          configMap:
            name: {{ include "flink.fullname" . }}
            defaultMode: 0777
            items:
              - key: docker-entrypoint.sh
                path: docker-entrypoint.sh
      initContainers:
        - name: init-zookeeper
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup {{ include "flink.zookeeper.fullname" . }}; do echo waiting for zookeeper; sleep 2; done"]
      containers:
        - name: pinpoint-jobmanager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - standalone-job
            - -p
            - "1"
            - "pinpoint-flink-job.jar -spring.profiles.active release"
          resources:
{{- toYaml .Values.resources | nindent 12 }}
          ports:
            - name: flink-job
              containerPort: 6123
            - name: flink-web
              containerPort: {{ .Values.serverPort}}
          envFrom:
            - configMapRef:
                name: {{ include "flink.fullname" .}}
          volumeMounts:
            - name: docker-bin
              mountPath: /docker-bin/docker-entrypoint.sh
              subPath: docker-entrypoint.sh

        - name: pinpoint-taskmanager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - taskmanager
          resources:
{{- toYaml .Values.resources | nindent 12 }}
          ports:
            - name: flink-task-1
              containerPort: 6121
            - name: flink-task-2
              containerPort: 6122
            - name: flink-task-clus
              containerPort: 19994
          envFrom:
            - configMapRef:
                name: {{ include "flink.fullname" .}}
          volumeMounts:
            - name: docker-bin
              mountPath: /docker-bin/docker-entrypoint.sh
              subPath: docker-entrypoint.sh
{{- end }}